server:
  port: 8888
spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/pareshvernekar/config-repo
          searchPaths:  eshop-inventory,eshop-shoppingcart
          username: fremontguy14@gmail.com
          password: Ch@meleo123n